# This workflow will build a Node.js project, run tests, and publish an npm package when something is pushed to the main branch.

name: Publish to npm

on:
  push:
    branches:
      - main
    paths:
      - "prettier.config.js"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js for NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Publish the package to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
